name: Build, Test, and Upload APK

on:
  push:
    branches: [main]

jobs:
  build_test_and_upload:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew

      - name: Test Decoding
        run: echo "${{ secrets.ENCODED_KEYSTORE }}" | base64 -d > signingKey.jks && file signingKey.jks

      - name: Bundle 'release' with Gradle
        run: ./gradlew bundleRelease
      
      - name: Sign AAB
        id: sign_aab
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.ENCODED_KEYSTORE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}  
      - run: echo "Build status report=${{ job.status }}."

      - name: Create symbolic link
        run: ln -s /home/runner/work/almate/almate/app/build/outputs/bundle/release/app-release.aab app-release.aab
    
      - name: Upload to Play Console
        id: upload
        uses: r0adkll/upload-google-play@v1.1.3
        continue-on-error: true
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.zexsys.almate
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: 'completed'

      - name: Upload App Bundle
        uses: actions/upload-artifact@v1
        with:
          name: aab
          path: ${{steps.sign_aab.outputs.signedReleaseFile}}

      - name: Check Upload Status
        if: always()
        run: |
          if [ -z "${{ steps.upload.outputs.status }}" ]; then
            echo "Upload failed with error: ${{ steps.upload.outputs.error }}"
          else
            echo "Upload status: ${{ steps.upload.outputs.status }}"
          fi
