name: Build, Test, and Upload APK

on:
  push:
    branches: [main]  # Adjust branch name as needed

jobs:
  build_test_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Decode Keystore
        run: echo ${{ secrets.ENCODED_KEYSTORE }} | base64 -d > release.keystore

      - name: Decode Google Services JSON
        run: echo ${{ secrets.ENCODED_GOOGLE_SERVICES_JSON }} | base64 -d > google-services.json

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=release.keystore \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: List APK Directory Contents
        run: ls -la app/build/outputs/apk/release

      - name: Upload to Play Console
        id: upload
        uses: r0adkll/upload-google-play@v1
        continue-on-error: true
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.zexsys.almate 
          releaseFile: app/release/app-release.apk
          track: internal 
          status: draft 

      # Check upload status and report
      - name: Check Upload Status
        if: always()
        run: echo "Upload status: ${{ steps.upload.outputs.status }}"
